In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures,StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('advanced.csv')
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
data.rename(columns={
    "fixed acidity":'fixed_acidity',
    'volatile acidity':'volaite_acidity',
    'citric acid':'citric_acid',
    'residual sugar':'residual_sugar',
    'chlorides':'chlorides',
    'free sulfur dioxide':'free_sulfur_dioxide',
    'total sulfur dioxide':'total_sulfur_dioxide',
    'density':'density',
    'pH' : 'pH',    
},inplace=True)

In [4]:
data.head()

fixed_acidity  volaite_acidity  citric_acid  residual_sugar  chlorides  \
0            7.4             0.70         0.00             1.9      0.076   
1            7.8             0.88         0.00             2.6      0.098   
2            7.8             0.76         0.04             2.3      0.092   
3           11.2             0.28         0.56             1.9      0.075   
4            7.4             0.70         0.00             1.9      0.076   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
x = data[['fixed_acidity','volaite_acidity',
          'citric_acid','residual_sugar','chlorides','free_sulfur_dioxide',
          'total_sulfur_dioxide','density','sulphates','alcohol']].values

In [6]:
y = data[['quality']].values

In [7]:
x

array([[ 7.4    ,  0.7    ,  0.     , ...,  0.9978 ,  0.56   ,  9.4    ],
       [ 7.8    ,  0.88   ,  0.     , ...,  0.9968 ,  0.68   ,  9.8    ],
       [ 7.8    ,  0.76   ,  0.04   , ...,  0.997  ,  0.65   ,  9.8    ],
       ...,
       [ 6.3    ,  0.51   ,  0.13   , ...,  0.99574,  0.75   , 11.     ],
       [ 5.9    ,  0.645  ,  0.12   , ...,  0.99547,  0.71   , 10.2    ],
       [ 6.     ,  0.31   ,  0.47   , ...,  0.99549,  0.66   , 11.     ]])

In [8]:
y

array([[5],
       [5],
       [5],
       ...,
       [6],
       [5],
       [6]])

In [9]:
# x = np.array(x).reshape(-1,1)

In [10]:
x

array([[ 7.4    ,  0.7    ,  0.     , ...,  0.9978 ,  0.56   ,  9.4    ],
       [ 7.8    ,  0.88   ,  0.     , ...,  0.9968 ,  0.68   ,  9.8    ],
       [ 7.8    ,  0.76   ,  0.04   , ...,  0.997  ,  0.65   ,  9.8    ],
       ...,
       [ 6.3    ,  0.51   ,  0.13   , ...,  0.99574,  0.75   , 11.     ],
       [ 5.9    ,  0.645  ,  0.12   , ...,  0.99547,  0.71   , 10.2    ],
       [ 6.     ,  0.31   ,  0.47   , ...,  0.99549,  0.66   , 11.     ]])

In [11]:
# y = np.array(y).reshape(-1,1)

In [12]:
x.shape

(1599, 10)

In [13]:
y.shape

(1599, 1)

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=100)

# Multiple Regression 

In [16]:
multi = LinearRegression()
multi.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
y_predict = multi.predict(x_test)

In [18]:
y_predict

array([[5.67561892],
       [6.39730921],
       [5.38818895],
       [4.94408424],
       [5.65244706],
       [6.76216282],
       [4.91162054],
       [6.10763964],
       [6.05711266],
       [6.52306149],
       [6.57598303],
       [5.3131621 ],
       [5.62319933],
       [5.14943702],
       [5.71912183],
       [4.86284963],
       [6.05165783],
       [5.05899709],
       [5.48097961],
       [5.41158172],
       [5.97339388],
       [5.39916465],
       [5.76907485],
       [6.04026589],
       [6.28681017],
       [6.12849477],
       [5.94599133],
       [5.19859342],
       [5.37305397],
       [5.62590328],
       [5.26776955],
       [5.41247617],
       [6.18534176],
       [5.94430271],
       [5.3914165 ],
       [5.83894131],
       [5.74987618],
       [5.46709876],
       [5.28241873],
       [4.99307714],
       [4.9589043 ],
       [6.12417618],
       [5.64832235],
       [5.72029309],
       [5.99156094],
       [5.7368527 ],
       [5.4382657 ],
       [6.334

In [21]:
import math
error = mean_squared_error(y_test,y_predict)
print('mean square error:\t',math.sqrt(error))
print('R value: \t',multi.score(x,y))

mean square error:	 0.6555434340292855
R value: 	 0.3570416876859024
